COLUMN PDB_NAME FORMAT a10
COLUMN DB_NAME FORMAT a10
COLUMN HOST_NAME FORMAT a30
SET LINESIZE 270 PAGESIZE 50
ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY-MM-DD HH24:MI:SS';

SELECT 'Pdb'     LIST,
       P.NAME         PDB_NAME,
       P.OPEN_MODE,
       P.RESTRICTED,
       D.NAME         DB_NAME,
       I.INSTANCE_NAME,
       I.HOST_NAME,
       I.STARTUP_TIME,
       I.STATUS
  FROM v$pdbs P, V$DATABASE D, v$instance I
  ORDER BY PDB_NAME;


set linesize 250
COLUMN DB_NAME FORMAT A10
COLUMN CON_ID FORMAT 999
COLUMN PDB_NAME FORMAT A15
COLUMN OPERATION FORMAT A16
COLUMN OP_TIMESTAMP FORMAT A20
COLUMN CLONED_FROM_PDB_NAME FORMAT A15
ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY-MM-DD HH24:MI:SS';


SELECT DB_NAME, CON_ID, PDB_NAME, MAX(OP_TIMESTAMP)
  FROM CDB_PDB_HISTORY
  WHERE CON_ID > 2
  GROUP BY DB_NAME, CON_ID, PDB_NAME
  ORDER BY CON_ID;
